### PR TITLE
Add connection status indicator

### PR DESCRIPTION
**Pull request by nevalsar**
- Box on bottom left shows ROS Master connection status
- Green colored when connected, yellow when disconnected
- Text display show connection states - Connected, Error, Closed

Possible improvements:
- Retry on disconnect without duplicating requests

Signed-off-by: Nevin Valsaraj nevin.valsaraj32@gmail.com

### CODE REVIEW

**Comment by nevalsar** [comment]
@ghostwriternr merge if you're okay with this.

**Comment by prudhvid** [comment]
This is okay. But instead of starting from scratch, @nevinvalsaraj @ghostwriternr cc @icyflame I would like all of you to build on existing framework like [ros-control-center](https://github.com/gaug-cns/ros-control-center)

**Comment by nevalsar** [comment]
@prudhvid This is pretty cool, I didn't know such a thing existed. Working on it.

**Comment by nevalsar** [comment]
@prudhvid The architecture for topic views is exactly what I was talking about. We better use [ros-control-center](https://github.com/gaug-cns/ros-control-center) as a base seeing how they have the structure in place.
@ghostwriternr please take note. Take some time to review the architecture and acquaint yourself with [angularjs](https://angularjs.org/) if required. The templates are surely going to make things a lot easier.

**Comment by icyflame** [comment]
@prudhvid That repo is great! :smile: I didn't something like this existed either. We should probably use that as a base, like Nevin said.

**Pull request merged**
